receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
  nginx:
    endpoint: "http://localhost:80/status"
    collection_interval: 10s
  filelog:
    include: ["var/log/nginx/*.log"]
    start_at: end
    operators:
      - type: json_parser
        timestamp:
          parse_from: body.time  
          layout: "%Y-%m-%dT%H:%M:%S%z"  
        parse_from: body  

processors:
  attributes:
    actions:
      - key: response_time
        action: insert
        from_attribute: body.response_time  
      - key: time
        action: insert
        from_attribute: body.time 
      - key: severity
        action: delete

  batch: {}

exporters:
  logging:
    verbosity: detailed 

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [attributes, batch]
      exporters: [logging]
